using Interviews.Domain.Entities.WorkflowTemplates;

namespace Interviews.Application.WorkflowTemplates.UpdateWorkflowTemplate;

public record UpdateWorkflowTemplateCommand(WorkflowTemplate WorkflowTemplate);